In [ ]:
pip install torch numpy

In [1]:
import torch
import numpy as np

In [3]:
t1 = torch.tensor([1,2]) # giving list as input to tensor
t2 = torch.tensor((3,1))
t3 = torch.tensor(np.array([3,2]))

In [4]:
print(t1)
print(t2)
print(t3)

tensor([1, 2])
tensor([3, 1])
tensor([3, 2])


In [5]:
# type(t1)
type(t3)

torch.Tensor